### ISSUE TITLE
define type by another function

### ISSUE THREAD

**Issue by elong0527** [iqis/foo#19]
May I ask why this definition is OK
 
```
size <- Q7::type( function(size){ }, s3 = "ggsd.size")
x <- size(1)
```

But below definition result in error. 
```
type_size <- function(size){ }
size <- Q7::type(type_size, s3 = "ggsd.size")
x <- size(1)
```

@nanxstats

**Comment by nanxstats** [comment]
I guess it is related to how the first argument `x` is processed in `type()`: https://github.com/iqis/Q7/blob/master/R/core.R#L21.

`deparse(substitute())` uses non-standard evaluation to capture the expression or function as character strings, so that you cannot use a variable there but have to write the actual content. This is the same behavior as in `library()`.

[adv-r](http://adv-r.had.co.nz/Computing-on-the-language.html) suggested providing an escape hatch or standard evaluation version but I'm not sure if it's worth it here.

**Comment by iqis** [comment]
Thanks @nanxstats. You are spot-on. This will be fixed.
