### ISSUE TITLE
Shall `magrittr` be in the suggest list?

### ISSUE THREAD

**Issue by elong0527** [iqis/foo#20]
It seems `magrittr` is not used in the function bodies. Shall it be moved to `Suggests:`? 

https://github.com/iqis/Q7/blob/d17ee96759b6ea3c4bdc7dd9225ee1fb959ba469/DESCRIPTION#L17

**Comment by iqis** [comment]
I've struggled a little bit when deciding to put `magrittr` into `Depends`... 

It looks like the prevailing usage of this field nowadays is limited to indicating R's version. Even for packages like `dplyr` which interface is designed to be almost exclusively used with with `magrittr` does not have it in `Depends`. 

I suppose you're right, it should be in `Suggests`. It should not be in `Imports`, either, because `Q7` itself is not written with `magrittr`.
